sonar.projectKey=Takiwi_PTPM_ma_nguon_mo
sonar.projectName=PTPM_ma_nguon_mo
sonar.organization=takiwi
sonar.projectVersion=1.0
sonar.host.url=sonarcloud.io
sonar.sources=cogs
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.venv/**,**/*.json,**/*.md,requirements.txt

sonar.language=py
sonar.sourceEncoding=UTF-8