# Thông tin Server (B?T BU?C ?? TR? V? MÁY LOCAL)
sonar.host.url=http://localhost:9000

# Token ??ng nh?p (B?n ?ã thêm ? b??c tr??c)
sonar.login=sqa_051ca774ae5e978ba09253b63c7fa8ecb03ab4d9

# Khóa d? án
sonar.projectKey=Study_Assistant_Bot
sonar.projectName=Study Assistant Bot
sonar.projectVersion=1.0

# ???ng d?n quét code
sonar.sources=.

# B? qua các th? m?c không c?n thi?t
sonar.exclusions=.venv/**,**/*.json,**/*.md,requirements.txt

# Ngôn ng?
sonar.language=py
sonar.sourceEncoding=UTF-8

