sonar.login=sqa_051ca774ae5e978ba09253b63c7fa8ecb03ab4d9

sonar.projectKey=Study_Assistant_Bot
sonar.projectName=Study Assistant Bot
sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=.venv/**,**/*.json,**/*.md,requirements.txt

sonar.language=py
sonar.sourceEncoding=UTF-8

